#!/bin/bash


#ORG_PATH="/home/ammirato/old_Data/";

#COMPRESS_PATH="/home/ammirato/Data/";

#ROOM_NAME="FB341_2";


#for image in $(ls $ORG_PATH$ROOM_NAME); do
#  convert -compress Zip $ORG_PATH$ROOM_NAME$image $COMPRESS_PATH$ROOM_NAME$image 
#done

mkdir -p $2


for image in $(ls $1); do
  convert -compress Zip $1$image $1$image 
done
