#!/bin/bash

ALL_DATA_PATH="/playpen/ammirato/Data/RohitData/"
ALL_METADATA_PATH="/playpen/ammirato/Data/RohitMetaData/"

RGB="rgb"
JPG_RGB="jpg_rgb"
RAW="raw_depth"
HIGH_RES="high_res_depth"
LABELS="labels"
VERIFIED_LABELS="verified_labels"
OBJECT_PC_LABELS="object_point_clouds"

TAR_DIR="tar_files"

TAR_EXTENSION=".tar"

RGB_FILENAME="rgb.tar"
UNREG_FILENAME="unreg_depth.tar"
RAW_FILENAME="raw_depth.tar"
ALL_JPG_FILENAME="all_jpg_rgb.tar"
PARTIAL_LABELS_FILENAME="partial_labels.tar"

function tar_dir {

  rm -rf $1/$TAR_DIR
  mkdir -p $1/$TAR_DIR
  tar -cf $1/$TAR_DIR/$RGB_FILENAME $1$RGB
  tar -cf $1/$TAR_DIR/$UNREG_FILENAME $1$UNREG
  tar -cf $1/$TAR_DIR/$RAW_FILENAME $1$RAW
}

function tar_all_jpg {
  #tar -cf $1/$ALL_JPG_FILENAME $1$JPG_RGB $1$RAW $1$HIGH_RES
  tar -C $2 -cf $2/$1/$1_$ALL_JPG_FILENAME $1/$JPG_RGB $1/$RAW $1/$HIGH_RES
}

function tar_partial_labels {
  #tar -cf $1/$ALL_JPG_FILENAME $1$JPG_RGB $1$RAW $1$HIGH_RES
  tar -C $2 -cf $2/$1/$1_$PARTIAL_LABELS_FILENAME $1/$LABELS/$VERIFIED_LABELS $1/$LABELS/$OBJECT_PC_LABELS
}


#for each room
for i in $(ls $ALL_DATA_PATH); do
  
  echo $i
#  tar_all_jpg $i $ALL_DATA_PATH
  tar_partial_labels $i $ALL_METADATA_PATH

  #tar -cvf $ALL_DATA_PATH$i$TAR_EXTENSION $ALL_DATA_PATH$i
  #write all the indices to files for rgb,unreg,raw
done




  test="rgb102K3.png"
  output=`echo $test | cut -d 'b' -f'2' `
  echo $output



#  echo $output >> test.txt
#  echo $output >> test.txt


