#!/bin/bash

ALL_DATA_PATH="/home/ammirato/Data_Compressed/"

RGB="/rgb"
UNREG="/unreg_depth"
RAW="/raw_depth"

RGB_FILENAME="/rgb.tar.gz"
UNREG_FILENAME="/unreg.tar.gz"
RAW_FILENAME="/raw.tar.gz"

function tar_dir {
  tar -cvzf $1$RGB_FILENAME $1$RGB
  tar -cvzf $1$UNREG_FILENAME $1$UNREG
  tar -cvzf $1$RAW_FILENAME $1$RAW
  
  #echo $1$RGB_FILENAME
  #echo $1$RGB
  #echo $1$UNREG_FILENAME 
  #echo $1$UNREG
  #echo $1$RAW_FILENAME 
  echo $1$RAW
}



#for each room
for i in $(ls $ALL_DATA_PATH); do
  
  echo $i
  tar_dir $ALL_DATA_PATH$i
  #write all the indices to files for rgb,unreg,raw
done




  test="rgb102K3.png"
  output=`echo $test | cut -d 'b' -f'2' `
  echo $output



#  echo $output >> test.txt
#  echo $output >> test.txt


